// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// tsfeats
NumericMatrix tsfeats(const int tslen, NumericMatrix& tsmat, const NumericMatrix& tsints);
RcppExport SEXP _tsrf_tsfeats(SEXP tslenSEXP, SEXP tsmatSEXP, SEXP tsintsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type tslen(tslenSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type tsmat(tsmatSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type tsints(tsintsSEXP);
    rcpp_result_gen = Rcpp::wrap(tsfeats(tslen, tsmat, tsints));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tsrf_tsfeats", (DL_FUNC) &_tsrf_tsfeats, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_tsrf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
